apiVersion: batch/v1
kind: Job
metadata:
  name: database-dump-demo
  # namespace: ddump
spec:
  template:
    metadata: 
      name: database-dump
      
    spec:
      containers:
      - name: database-dump
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${FULL_IMAGE_TAG}
        # image: 720641203850.dkr.ecr.us-east-2.amazonaws.com/movie-app:2a3151f5a9be6ce32f58b5660af6b63471c16b9e
        env:
            - name: PASSWORD
              value: "env-var"
        #     - name: HOST
        #       value: "placeholder"
        #     - name: PASSWORD
        #       value: "Placeholder"
        #     - name: HOST
        #       value: "placeholder"
      restartPolicy: Never


