apiVersion: batch/v1
kind: Job
metadata:
  name: database-dump-demo
spec:
  template:
    metadata: 
      name: database-dump-demo
    spec:
      containers:
      - name: database-dump-demo
        image: ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}
        # image: 720641203850.dkr.ecr.us-east-2.amazonaws.com/movie-app:${IMAGE_TAG}
        env:
            - name: PASSWORD
              value: "env-var"
        #     - name: HOST
        #       value: "placeholder"
        #     - name: PASSWORD
        #       value: "Placeholder"
        #     - name: HOST
        #       value: "placeholder"
      restartPolicy: Never


