# This workfloww is to to build a containerized application, 
# push it to Amazon Elastic Container Registry (ECR), 
# and deploy it to EKS.

name: Deploy to Amazon EKS

on:
  push:
    branches: [ main ]
  release:
    types:
      - created
  workflow_dispatch:
  


env:
  AWS_REGION: us-east-1                # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: image-services          # set this to your Amazon ECR repository name
  KUBECONFIG: KUBECONFIG
  IMAGE_NAME: image-services
  BRANCH: BRANCH

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
        
# #       - name: Checkout
# #         uses: actions/checkout@v2
#       - name: testing code
#         run: echo "${GITHUB_REF##*/}"
      
#       - name: Extract branch name
#         run: echo "env.BRANCH"
#       - name: testing
#         if: contains(env.BRANCH,'master')
#         run: echo "should be printed"
      
        
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
        
      - name: Set environmental variables for image branch
        run: echo "BRANCH1=${GITHUB_REF##*/}" >> $GITHUB_ENV
        
      - name: test output
        run: echo "$BRANCH1"
        
      - name: Set environmental variables for image branch
        if: contains(steps.extract_branch.outputs.branch,'master')
        run: echo "BRANCH=${{steps.extract_branch.outputs.branch}}" >> $GITHUB_ENV
        
      - name: test output
        run: echo "$BRANCH"
        
#       - name: set env 
#       - name: Set env
#       echo "{name}={value}" >> $GITHUB_ENV
#       run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
      


   
