# This workfloww is to to build a containerized application, 
# push it to Amazon Elastic Container Registry (ECR), 
# and deploy it to EKS.

name: Deploy to Amazon EKS

on:
  push:
    branches: [ main ]
  release:
    types:
      - created
  workflow_dispatch:
  


env:
  AWS_REGION: us-east-1                # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: image-services          # set this to your Amazon ECR repository name
  KUBECONFIG: KUBECONFIG
  IMAGE_NAME: image-services
  BRANCH: BRANCH

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
        
#       - name: Checkout
#         uses: actions/checkout@v2
      - name: testing code
        run: echo "${GITHUB_REF##*/}"
      
#       - name: Extract branch name
#         shell: bash
#         run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
#         id: extract_branch

      - name: check branch
        if: contains( ${GITHUB_REF##*/} ,"master")
        run: echo "i contain image"
        

   
